name: dagre
version: 0.0.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Graph layout for Dart
dependencies:
  graphlib:
    path: ../graphlib
  quiver: any
dev_dependencies:
  graphlib_dot:
    path: ../graphlib_dot
